collarserver/collarserver/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shock/', include('shock.urls')),
]

collarserver/shock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from rest_framework import routers, serializers, viewsets

from . import control

urlpatterns = [
    path('', control.controller),
    path('api/', control.api_shock),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', auth_views.LoginView.as_view()),
]

collarserver/shock/models.py
from django.db import models
from enum import IntEnum
from django.core.validators import MaxValueValidator, MinValueValidator

MINPOWER = 0
MAXPOWER = 99
    
class Function(IntEnum):
    SHOCK = 1
    VIBRATE = 2
    SOUND = 3

string_to_func = {"shock": Function.SHOCK, "vibrate": Function.VIBRATE, "sound": Function.SOUND}

int_to_func = {1: Function.SHOCK, 2: Function.VIBRATE, 3: Function.SOUND}
func_to_int = {Function.SHOCK: 1, Function.VIBRATE: 2, Function.SOUND: 3}

collarserver/shock/forms.py
from .shock import MINPOWER, MAXPOWER
from django import forms
from .models import Function

mode_choices = (
    (int(Function.SHOCK), "Shock"),
    (int(Function.VIBRATE), "Vibrate"),
    (int(Function.SOUND), "Sound")
)

class ShockForm(forms.Form):
    duration = forms.FloatField(label='Duration', min_value=0, max_value=10, initial=1)
    power = forms.IntegerField(label='Power', min_value=MINPOWER, max_value=MAXPOWER, initial=0)
    mode = forms.ChoiceField(choices=mode_choices, initial=Function.SHOCK)
    
class PowerConfigForm(forms.Form):
    shock_power = forms.IntegerField(label='Shock power', min_value=MINPOWER, max_value=MAXPOWER)
    vibration_power = forms.IntegerField(label='Vibration power', min_value=MINPOWER, max_value=MAXPOWER)
    mode = forms.ChoiceField(choices=mode_choices)

collarserver/shock/templates/collarserver/config.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Shock collar calibration</title>
    </head>
    <body>
        <form action="/config/" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Calibate power level">
        </form>
        <a href="/shock/">Shock</a>
    </body>
</html>

collarserver/shock/templates/collarserver/controller.html
<!DOCTYPE html>
<html>
    <head>
        <style>
.shockButton {
  display: block;
  width: 100%;
  height: 60px;
  background-color: #04AA6D; /* Green background */
  border: 1px solid green; /* Green border */
  color: white; /* White text */
  padding: 10px 24px; /* Some padding */
  cursor: pointer; /* Pointer/hand icon */
  float: left; /* Float the buttons side by side */
}

.btn-group {
  width: 100%;
}

.btn-group button {
  background-color: #04AA6D; /* Green background */
  border: 1px solid green; /* Green border */
  color: white; /* White text */
  padding: 10px 24px; /* Some padding */
  cursor: pointer; /* Pointer/hand icon */
  float: left; /* Float the buttons side by side */
  height: 100%;
  font-size: 15vh;
}

.btn-group button:not(:last-child) {
  border-right: none; /* Prevent double borders */
}

/* Clear floats (clearfix hack) */
.btn-group:after {
  content: "";
  clear: both;
  display: table;
}

/* Add a background color on hover */
.btn-group button:hover, .shockButton:hover {
  background-color: #3e8e41;
}

label {
  font-size: 5vh
}

input {
  height: 5vh;
  font-size: 5vh;
  width: 5vw;
}

select {
  height: 5vh;
  font-size: 5vh;
  width: 9vw;
}

</style>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Shock collar controller</title>
    </head>
    <body>
      <span>Collar is {% if on %}
        <span style="color:green">on</span>
        {% else %}<span style="color:red">off</span>
        {% endif %}</span>
        <form action="/shock/" method="post">
          {% csrf_token %}
            <tr>
        <th><label for="id_duration">Duration:</label></th>
    <td>
      <input type="number" name="duration" value="{{ form.duration.value }}" min="0" max="10" step="any" required id="id_duration">
      <div class="btn-group">
            <button type="button" style="width:50%" onclick="addToDuration(-1)">-1s</button>
            <button type="button" style="width:50%" onclick="addToDuration(1)">+1s</button>
            </div>
    </td>
  </tr>
  <tr>
    <th><label for="id_power">Power:</label></th>
    <td>
      <input type="number" name="power" value="{{ form.power.value }}" min="0" max="99" required id="id_power">
      <div class="btn-group">
            <button type="button" style="width:25%" onclick="addToPower(-5)">-5</button>
            <button type="button" style="width:25%" onclick="addToPower(-1)">-1</button>
            <button type="button" style="width:25%" onclick="addToPower(1)">+1</button>
            <button type="button" style="width:25%" onclick="addToPower(5)">+5</button>
            </div>
    </td>
  </tr>
  <tr>
    <th><label for="id_mode">Mode:</label></th>
    <td>
      {{ form.mode }}
</select>
      <div class = "btn-group">
            <button type="button" style="width:33.333%" onclick="setMode(1)">Shock</button>
            <button type="button" style="width:33.333%" onclick="setMode(2)">Vibrate</button>
            <button type="button" style="width:33.333%" onclick="setMode(3)">Sound</button>
            </div>
    </td>
  </tr>
  <div class="btn-group">
  <button type="submit" class="shockButton">Activate</button>
  </div>
        </form>
    </body>
    <script type="text/javascript">
    function addToPower(i) {
      var newVal = (parseInt(document.getElementById("id_power").value) + i)%100;
      if (newVal < 0) {
      	newVal = 100 + newVal;
      }
      document.getElementById("id_power").value = newVal;
    }
    function addToDuration(i) {
      var newVal = parseInt(document.getElementById("id_duration").value) + i;
      if (newVal < 0) {
        newVal = 0;
      }
      if (newVal > 10) {
        newVal = 10;
      }
      document.getElementById("id_duration").value = newVal;
    }
    function setMode(i) {
    	document.getElementById("id_mode").value = i;
    }
    </script>
</html>